common:
  http_address: 0.0.0.0
  http_port: 8443
  key_factor: "ywlSRb80TaCQ4b7b"
database:
  driver: mysql
  url: "tcp(127.0.0.1:3306)/mmalls?charset=utf8&parseTime=true&charset=utf8&loc=Local"
  user_name: goman
  password: "c78jt2NGOwtfmOZs5CQcOEwCsMQjgf6ZrNQzuwtHmHo="
jwt:
  public_key: conf/jwt_pub.pem
  private_key: conf/jwt_pri.pem
  enable: false